<?php  $topdir = "../"; include("../../pageHeader.php"); ?>
<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/72.jpg" class="fancybox" rel="fancy-group" id="img73"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/72-thumb.jpg" alt="Group photo. Joey, Jenny, Ryan, Paul, and Stuart (left to right), Nick (below)." title="Group photo. Joey, Jenny, Ryan, Paul, and Stuart (left to right), Nick (below)." width="211" height="153" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/73.jpg" class="fancybox" rel="fancy-group" id="img74"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/73-thumb.jpg" alt="Ryan with a huge Juniper tree." title="Ryan with a huge Juniper tree." width="211" height="317" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/74.jpg" class="fancybox" rel="fancy-group" id="img75"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/74-thumb.jpg" alt="The parking lot for Waterhouse lake. So begins our road hiking." title="The parking lot for Waterhouse lake. So begins our road hiking." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/75.jpg" class="fancybox" rel="fancy-group" id="img76"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/75-thumb.jpg" alt="Flower." title="Flower." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/76.jpg" class="fancybox" rel="fancy-group" id="img77"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/76-thumb.jpg" alt="Ryan and Nick. We aren't too happy about the road hiking, so we try to figure out an alternative route." title="Ryan and Nick. We aren't too happy about the road hiking, so we try to figure out an alternative route." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/77.jpg" class="fancybox" rel="fancy-group" id="img78"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/77-thumb.jpg" alt="Jenny hiking." title="Jenny hiking." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/78.jpg" class="fancybox" rel="fancy-group" id="img79"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/78-thumb.jpg" alt="Logging roads are interesting &ETH;&Ecirc;they wind all over the place to let huge trucks make the grade (pun intended). They also are a pain to hike on. It didn't take us long to realize that we could cut some distance off if we did a straight shot." title="Logging roads are interesting &ETH;&Ecirc;they wind all over the place to let huge trucks make the grade (pun intended). They also are a pain to hike on. It didn't take us long to realize that we could cut some distance off if we did a straight shot." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/79.jpg" class="fancybox" rel="fancy-group" id="img80"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/79-thumb.jpg" alt="Bushwhacking through to avoid roads. The balancing act is easier then trying to 'whack the grass." title="Bushwhacking through to avoid roads. The balancing act is easier then trying to 'whack the grass." width="211" height="114" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/80.jpg" class="fancybox" rel="fancy-group" id="img81"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/80-thumb.jpg" alt="Random forest clearing." title="Random forest clearing." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/81.jpg" class="fancybox" rel="fancy-group" id="img82"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/81-thumb.jpg" alt="The triumphant return to Pinecrest." title="The triumphant return to Pinecrest." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/82.jpg" class="fancybox" rel="fancy-group" id="img83"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/82-thumb.jpg" alt="The boat launching area at Pinecrest." title="The boat launching area at Pinecrest." width="211" height="129" /></a>
		<p id="pageNav"><a id="next" href="page6.php">next page</a></p><h3 id="endText">No more photos!</h3><?php include("../../pageFooter.php");  ?>