<?php  $topdir = "../"; include("../../pageHeader.php"); ?>
<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/54.jpg" class="fancybox" rel="fancy-group" id="img55"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/54-thumb.jpg" alt="&quot;Common guys, let's go!&quot; Jenny complained." title="&quot;Common guys, let's go!&quot; Jenny complained." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/55.jpg" class="fancybox" rel="fancy-group" id="img56"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/55-thumb.jpg" alt="Granite is just nifty." title="Granite is just nifty." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/56.jpg" class="fancybox" rel="fancy-group" id="img57"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/56-thumb.jpg" alt="Ryan Andrews." title="Ryan Andrews." width="211" height="157" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/57.jpg" class="fancybox" rel="fancy-group" id="img58"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/57-thumb.jpg" alt="Glaciers must have been quite a sight to see here. This white line is completely natural, and completely weird." title="Glaciers must have been quite a sight to see here. This white line is completely natural, and completely weird." width="211" height="127" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/58-featured.jpg" class="fancybox featured" rel="fancy-group" id="img59"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/58-featured-thumb.jpg" alt="We eventually got to a point were we could follow the river up to Waterhouse lake. The water level was very low this year, and where there usually is a river, was just really cool, smooth, sculpted, rock." title="We eventually got to a point were we could follow the river up to Waterhouse lake. The water level was very low this year, and where there usually is a river, was just really cool, smooth, sculpted, rock." width="427" height="283" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/59.jpg" class="fancybox" rel="fancy-group" id="img60"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/59-thumb.jpg" alt="The water was not flowing." title="The water was not flowing." width="211" height="181" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/60.jpg" class="fancybox" rel="fancy-group" id="img61"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/60-thumb.jpg" alt="The low water level makes it really easy to hike up to Waterhouse lake &ETH;&Ecirc;you can walk right through the river." title="The low water level makes it really easy to hike up to Waterhouse lake &ETH;&Ecirc;you can walk right through the river." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/61-featured.jpg" class="fancybox featured" rel="fancy-group" id="img62"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/61-featured-thumb.jpg" alt="Nick Laskowski." title="Nick Laskowski." width="427" height="283" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/62.jpg" class="fancybox" rel="fancy-group" id="img63"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/62-thumb.jpg" alt="Nick nearly at the base of Waterhouse lake." title="Nick nearly at the base of Waterhouse lake." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/63.jpg" class="fancybox" rel="fancy-group" id="img64"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/63-thumb.jpg" alt="After all day getting our balls sweated off, washing up in the lake felt great &ETH;&Ecirc;we were pretty quick to dump our packs and get on that." title="After all day getting our balls sweated off, washing up in the lake felt great &ETH;&Ecirc;we were pretty quick to dump our packs and get on that." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/64.jpg" class="fancybox" rel="fancy-group" id="img65"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/64-thumb.jpg" alt="Valleys that run East-West look pretty cool at sunset." title="Valleys that run East-West look pretty cool at sunset." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/65.jpg" class="fancybox" rel="fancy-group" id="img66"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/65-thumb.jpg" alt="Sunset at Waterhouse lake." title="Sunset at Waterhouse lake." width="211" height="123" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/66-featured.jpg" class="fancybox featured" rel="fancy-group" id="img67"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/66-featured-thumb.jpg" alt="There are a lot of stumps in one corner of the lake, most of them partially in the water." title="There are a lot of stumps in one corner of the lake, most of them partially in the water." width="427" height="268" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/67.jpg" class="fancybox" rel="fancy-group" id="img68"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/67-thumb.jpg" alt="Grass." title="Grass." width="211" height="107" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/68.jpg" class="fancybox" rel="fancy-group" id="img69"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/68-thumb.jpg" alt="The last moments of the sunrise." title="The last moments of the sunrise." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/69-featured.jpg" class="fancybox featured" rel="fancy-group" id="img70"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/69-featured-thumb.jpg" alt="" title="" width="1075" height="210" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/70.jpg" class="fancybox" rel="fancy-group" id="img71"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/70-thumb.jpg" alt="Nick and Stuart on the trail." title="Nick and Stuart on the trail." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/71.jpg" class="fancybox" rel="fancy-group" id="img72"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/71-thumb.jpg" alt="Group photo. Nick, Jenny, Stuart, Ryan, Paul, and Joey (left to right). The valley of the SoFoStan below us." title="Group photo. Nick, Jenny, Stuart, Ryan, Paul, and Joey (left to right). The valley of the SoFoStan below us." width="211" height="104" /></a>
		<p id="pageNav"><a id="next" href="page5.php">next page</a></p><?php include("../../pageFooter.php");  ?>