<?php  $topdir = "../"; include("../../pageHeader.php"); ?>
<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/18.jpg" class="fancybox" rel="fancy-group" id="img19"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/18-thumb.jpg" alt="" title="" width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/19-featured.jpg" class="fancybox featured" rel="fancy-group" id="img20"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/19-featured-thumb.jpg" alt="Pinecrest at Sunset as seen from Cleo's bath." title="Pinecrest at Sunset as seen from Cleo's bath." width="1075" height="350" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/20-featured.jpg" class="fancybox featured" rel="fancy-group" id="img21"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/20-featured-thumb.jpg" alt="Jenny looking stoic at Cleo's." title="Jenny looking stoic at Cleo's." width="427" height="283" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/21.jpg" class="fancybox" rel="fancy-group" id="img22"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/21-thumb.jpg" alt="Nick setting up breakfast. Camping on granite is awesome!" title="Nick setting up breakfast. Camping on granite is awesome!" width="211" height="130" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/22.jpg" class="fancybox" rel="fancy-group" id="img23"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/22-thumb.jpg" alt="The whole group &ETH; about to hit granite world." title="The whole group &ETH; about to hit granite world." width="211" height="157" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/23.jpg" class="fancybox" rel="fancy-group" id="img24"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/23-thumb.jpg" alt="Up, up and away." title="Up, up and away." width="211" height="101" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/24.jpg" class="fancybox" rel="fancy-group" id="img25"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/24-thumb.jpg" alt="Carems, ducks, trail markers&Eacute; we've got a few of them out there. Not that that makes them easy to find or anything." title="Carems, ducks, trail markers&Eacute; we've got a few of them out there. Not that that makes them easy to find or anything." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/25.jpg" class="fancybox" rel="fancy-group" id="img26"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/25-thumb.jpg" alt="Paul, excited that he got up the latest scramble, or that we got to our first Juniper tree?" title="Paul, excited that he got up the latest scramble, or that we got to our first Juniper tree?" width="211" height="162" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/26.jpg" class="fancybox" rel="fancy-group" id="img27"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/26-thumb.jpg" alt="Ryan need to have his photo taken by the juniper tree." title="Ryan need to have his photo taken by the juniper tree." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/27.jpg" class="fancybox" rel="fancy-group" id="img28"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/27-thumb.jpg" alt="&Eacute;So Jenny had to have her photo taken by the Juniper tree too." title="&Eacute;So Jenny had to have her photo taken by the Juniper tree too." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/28.jpg" class="fancybox" rel="fancy-group" id="img29"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/28-thumb.jpg" alt="There are trails on the granite&Eacute; really! Mostly. Sorta. Kinda. If you look hard. You have to be creative really. (really)." title="There are trails on the granite&Eacute; really! Mostly. Sorta. Kinda. If you look hard. You have to be creative really. (really)." width="211" height="224" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/29.jpg" class="fancybox" rel="fancy-group" id="img30"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/29-thumb.jpg" alt="Stuart Naiper." title="Stuart Naiper." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/30.jpg" class="fancybox" rel="fancy-group" id="img31"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/30-thumb.jpg" alt="Ryan loves him the Juniper trees." title="Ryan loves him the Juniper trees." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/31-featured.jpg" class="fancybox featured" rel="fancy-group" id="img32"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/31-featured-thumb.jpg" alt="The granite is the fastest way (read: only) to the top of the SoFoStan valley." title="The granite is the fastest way (read: only) to the top of the SoFoStan valley." width="427" height="349" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/32.jpg" class="fancybox" rel="fancy-group" id="img33"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/32-thumb.jpg" alt="Once we got to the top of the valley, it was just a matter of traversing. Which took longer than we expected." title="Once we got to the top of the valley, it was just a matter of traversing. Which took longer than we expected." width="211" height="157" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/33.jpg" class="fancybox" rel="fancy-group" id="img34"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/33-thumb.jpg" alt="Nick loved to take scouts across this stone ledge &ETH;&Ecirc;just because it was fun to challenge/torture them. Mountain goat, Jenny brown had no trouble here." title="Nick loved to take scouts across this stone ledge &ETH;&Ecirc;just because it was fun to challenge/torture them. Mountain goat, Jenny brown had no trouble here." width="211" height="317" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/34.jpg" class="fancybox" rel="fancy-group" id="img35"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/34-thumb.jpg" alt="Paul got a bit tired &ETH; but like the bear that he is, kept hiking." title="Paul got a bit tired &ETH; but like the bear that he is, kept hiking." width="211" height="100" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/35.jpg" class="fancybox" rel="fancy-group" id="img36"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/35-thumb.jpg" alt="The problem with the top on the granite, is that it's never really the top. The whole valley keeps going up." title="The problem with the top on the granite, is that it's never really the top. The whole valley keeps going up." width="211" height="176" /></a>
		<p id="pageNav"><a id="next" href="page3.php">next page</a></p><?php include("../../pageFooter.php");  ?>