<?php  $topdir = "../"; include("../../pageHeader.php"); ?>
<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/36.jpg" class="fancybox" rel="fancy-group" id="img37"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/36-thumb.jpg" alt="Paul, tired." title="Paul, tired." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/37.jpg" class="fancybox" rel="fancy-group" id="img38"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/37-thumb.jpg" alt="Juniper trees are amazing. They grow in the middle of nothing, live for thousands of years, and have these weird ol' shapes. (oh, and then there's the gin thing too.)" title="Juniper trees are amazing. They grow in the middle of nothing, live for thousands of years, and have these weird ol' shapes. (oh, and then there's the gin thing too.)" width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/38.jpg" class="fancybox" rel="fancy-group" id="img39"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/38-thumb.jpg" alt="Paul, hiking." title="Paul, hiking." width="211" height="109" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/39.jpg" class="fancybox" rel="fancy-group" id="img40"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/39-thumb.jpg" alt="Hiking across granite land." title="Hiking across granite land." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/40.jpg" class="fancybox" rel="fancy-group" id="img41"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/40-thumb.jpg" alt="Paul hiking across granite land." title="Paul hiking across granite land." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/41.jpg" class="fancybox" rel="fancy-group" id="img42"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/41-thumb.jpg" alt="Granite is just nifty." title="Granite is just nifty." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/42.jpg" class="fancybox" rel="fancy-group" id="img43"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/42-thumb.jpg" alt="Nick Laskowski." title="Nick Laskowski." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/43.jpg" class="fancybox" rel="fancy-group" id="img44"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/43-thumb.jpg" alt="We found this really sweet rock &Agrave;collection? A tone of huge boulders had fallen together to make a small cave &ETH; complete with a skylight." title="We found this really sweet rock &Agrave;collection? A tone of huge boulders had fallen together to make a small cave &ETH; complete with a skylight." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/44.jpg" class="fancybox" rel="fancy-group" id="img45"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/44-thumb.jpg" alt="See, skylight!" title="See, skylight!" width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/45.jpg" class="fancybox" rel="fancy-group" id="img46"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/45-thumb.jpg" alt="The pointed rock is something of a mystery. It looks like a shark fin." title="The pointed rock is something of a mystery. It looks like a shark fin." width="211" height="268" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/46.jpg" class="fancybox" rel="fancy-group" id="img47"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/46-thumb.jpg" alt="Group photo in the cave like area. It was really hard to find footing in there." title="Group photo in the cave like area. It was really hard to find footing in there." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/47.jpg" class="fancybox" rel="fancy-group" id="img48"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/47-thumb.jpg" alt="" title="" width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/48.jpg" class="fancybox" rel="fancy-group" id="img49"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/48-thumb.jpg" alt="Shark fin skylight." title="Shark fin skylight." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/49.jpg" class="fancybox" rel="fancy-group" id="img50"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/49-thumb.jpg" alt="Checking out the 'cave' was a great opportunity for rest. Nick puts on his most attractive face." title="Checking out the 'cave' was a great opportunity for rest. Nick puts on his most attractive face." width="211" height="157" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/50.jpg" class="fancybox" rel="fancy-group" id="img51"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/50-thumb.jpg" alt="Stuart Naiper." title="Stuart Naiper." width="211" height="140" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/51.jpg" class="fancybox" rel="fancy-group" id="img52"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/51-thumb.jpg" alt="Nick and Paul. Nick was tired too." title="Nick and Paul. Nick was tired too." width="211" height="180" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/52.jpg" class="fancybox" rel="fancy-group" id="img53"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/52-thumb.jpg" alt="Granite is just nifty." title="Granite is just nifty." width="211" height="317" /></a>
		<a href="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/53.jpg" class="fancybox" rel="fancy-group" id="img54"><img src="http://localhost:8888/joeybakerphoto/a/vacationtrip/photos/thumbs/53-thumb.jpg" alt="Paul, Nick, Ryan and Jenny." title="Paul, Nick, Ryan and Jenny." width="211" height="140" /></a>
		<p id="pageNav"><a id="next" href="page4.php">next page</a></p><?php include("../../pageFooter.php");  ?>